# Generated by Django 5.1.15 on 2026-09-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_seed_preset_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexercise',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedexercise',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
